name: Poke voice
on:
  push:
    branches:
      - main
jobs:
  run-bst:
    env:
      VIRTUAL_DEVICE_TOKEN: ${{ secrets.VIRTUAL_DEVICE_TOKEN }}
      BESPOKEN_API_BASE_URL: ${{ secrets.BESPOKEN_API_BASE_URL }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test